### ISSUE TITLE
Will DetailCaps-100 be open-source?

### ISSUE THREAD

**Issue by ShaoqLin** [foundation-multimodal-models/CAPTURE#3]
Hello,
Thanks for your great work.
I was wondering whether the DetailCaps-100 will be released.

Best regards
:)

**Comment by Dousia** [comment]
Than you for your interest in our work. I am sorry that we cannot release the DetailCaps-100 benchmark mentioned in this work, due to certain regulations. In the following months, however, we will release a new version of the DetailCaps benchmark with ground truths corrected by human experts. 
Please let me know if you have any further questions.
